local addonName, PST = ...

PST = PST or {}
_G[addonName] = PST
PST.Data = PST.Data or {}

PST.Data.Locale = "enUS"

PST.Data.Professions = {
    Herbalism = "Herbalism",
    Lockpicking = "Lockpicking",
    Mining = "Mining",
    Skinning = "Skinning",
}

PST.Data.TrainingRanks = {
    Herbalism = {
        [75] = { rank = "Journeyman", skill = 50, level = 10 },
        [150] = { rank = "Expert", skill = 125, level = 20 },
        [225] = { rank = "Artisan", skill = 200, level = 35 },
        [300] = { rank = "Master", skill = 275, level = 50 },
    },
    Mining = {
        [75] = { rank = "Journeyman", skill = 50, level = 10 },
        [150] = { rank = "Expert", skill = 125, level = 20 },
        [225] = { rank = "Artisan", skill = 200, level = 35 },
        [300] = { rank = "Master", skill = 275, level = 50 },
    },
    Skinning = {
        [75] = { rank = "Journeyman", skill = 50, level = 10 },
        [150] = { rank = "Expert", skill = 125, level = 20 },
        [225] = { rank = "Artisan", skill = 200, level = 35 },
        [300] = { rank = "Master", skill = 275, level = 50 },
    },
}

PST.Data.MiningNodes = {
    ["Copper Vein"] = 1,
    ["Tin Vein"] = 65,
    ["Silver Vein"] = 75,
    ["Iron Deposit"] = 125,
    ["Gold Vein"] = 155,
    ["Mithril Deposit"] = 175,
    ["Truesilver Deposit"] = 230,
    ["Dark Iron Deposit"] = 230,
    ["Small Thorium Vein"] = 245,
    ["Rich Thorium Vein"] = 275,
    ["Hakkari Thorium Vein"] = 245,
    ["Ooze Covered Iron Deposit"] = 125,
    ["Ooze Covered Silver Vein"] = 75,
    ["Ooze Covered Gold Vein"] = 155,
    ["Ooze Covered Mithril Deposit"] = 175,
    ["Ooze Covered Truesilver Deposit"] = 230,
    ["Ooze Covered Thorium Vein"] = 245,
    ["Ooze Covered Rich Thorium Vein"] = 275,
    ["Small Obsidian Chunk"] = 305,
    ["Large Obsidian Chunk"] = 305,
    ["Fel Iron Deposit"] = 275,
    ["Adamantite Deposit"] = 325,
    ["Rich Adamantite Deposit"] = 350,
    ["Khorium Vein"] = 375,
    ["Ancient Gem Vein"] = 375,
}

PST.Data.MiningAliases = {
    ["Copper"] = "Copper Vein",
    ["Tin"] = "Tin Vein",
    ["Silver"] = "Silver Vein",
    ["Iron"] = "Iron Deposit",
    ["Gold"] = "Gold Vein",
    ["Mithril"] = "Mithril Deposit",
    ["Truesilver"] = "Truesilver Deposit",
    ["Dark Iron"] = "Dark Iron Deposit",
    ["Small Thorium"] = "Small Thorium Vein",
    ["Rich Thorium"] = "Rich Thorium Vein",
    ["Fel Iron"] = "Fel Iron Deposit",
    ["Adamantite"] = "Adamantite Deposit",
    ["Rich Adamantite"] = "Rich Adamantite Deposit",
    ["Khorium"] = "Khorium Vein",
    ["Ancient Gem"] = "Ancient Gem Vein",
}

PST.Data.MiningReferenceItems = {
    ["Copper Vein"] = 2770,
    ["Tin Vein"] = 2771,
    ["Silver Vein"] = 2775,
    ["Iron Deposit"] = 2772,
    ["Gold Vein"] = 2776,
    ["Mithril Deposit"] = 3858,
    ["Truesilver Deposit"] = 7911,
    ["Dark Iron Deposit"] = 11370,
    ["Small Thorium Vein"] = 10620,
    ["Rich Thorium Vein"] = 10620,
    ["Hakkari Thorium Vein"] = 10620,
    ["Ooze Covered Iron Deposit"] = 2772,
    ["Ooze Covered Silver Vein"] = 2775,
    ["Ooze Covered Gold Vein"] = 2776,
    ["Ooze Covered Mithril Deposit"] = 3858,
    ["Ooze Covered Truesilver Deposit"] = 7911,
    ["Ooze Covered Thorium Vein"] = 10620,
    ["Ooze Covered Rich Thorium Vein"] = 10620,
    ["Small Obsidian Chunk"] = 22202,
    ["Large Obsidian Chunk"] = 22203,
    ["Fel Iron Deposit"] = 23424,
    ["Adamantite Deposit"] = 23425,
    ["Rich Adamantite Deposit"] = 23425,
    ["Khorium Vein"] = 23426,
    ["Ancient Gem Vein"] = 23117,
}

PST.Data.HerbReferenceItems = {
    ["Peacebloom"] = 2447,
    ["Silverleaf"] = 765,
    ["Earthroot"] = 2449,
    ["Mageroyal"] = 785,
    ["Briarthorn"] = 2450,
    ["Stranglekelp"] = 3820,
    ["Bruiseweed"] = 2453,
    ["Wild Steelbloom"] = 3355,
    ["Grave Moss"] = 3369,
    ["Kingsblood"] = 3356,
    ["Liferoot"] = 3357,
    ["Fadeleaf"] = 3818,
    ["Goldthorn"] = 3821,
    ["Khadgar's Whisker"] = 3358,
    ["Wintersbite"] = 3819,
    ["Firebloom"] = 4625,
    ["Purple Lotus"] = 8831,
    ["Arthas' Tears"] = 8836,
    ["Sungrass"] = 8838,
    ["Blindweed"] = 8839,
    ["Ghost Mushroom"] = 8845,
    ["Gromsblood"] = 8846,
    ["Golden Sansam"] = 13464,
    ["Dreamfoil"] = 13463,
    ["Mountain Silversage"] = 13465,
    ["Plaguebloom"] = 13466,
    ["Icecap"] = 13467,
    ["Black Lotus"] = 13468,
    ["Felweed"] = 22785,
    ["Dreaming Glory"] = 22786,
    ["Ragveil"] = 22787,
    ["Terocone"] = 22789,
    ["Flame Cap"] = 22788,
    ["Ancient Lichen"] = 22790,
    ["Netherbloom"] = 22791,
    ["Nightmare Vine"] = 22792,
    ["Mana Thistle"] = 22793,
}

PST.Data.HerbNodes = {
    ["Peacebloom"] = 1,
    ["Silverleaf"] = 1,
    ["Earthroot"] = 15,
    ["Mageroyal"] = 50,
    ["Briarthorn"] = 70,
    ["Stranglekelp"] = 85,
    ["Bruiseweed"] = 100,
    ["Wild Steelbloom"] = 115,
    ["Grave Moss"] = 120,
    ["Kingsblood"] = 125,
    ["Liferoot"] = 150,
    ["Fadeleaf"] = 160,
    ["Goldthorn"] = 170,
    ["Khadgar's Whisker"] = 185,
    ["Wintersbite"] = 195,
    ["Firebloom"] = 205,
    ["Purple Lotus"] = 210,
    ["Arthas' Tears"] = 220,
    ["Sungrass"] = 230,
    ["Blindweed"] = 235,
    ["Ghost Mushroom"] = 245,
    ["Gromsblood"] = 250,
    ["Golden Sansam"] = 260,
    ["Dreamfoil"] = 270,
    ["Mountain Silversage"] = 280,
    ["Plaguebloom"] = 285,
    ["Icecap"] = 290,
    ["Black Lotus"] = 300,
    ["Felweed"] = 300,
    ["Dreaming Glory"] = 315,
    ["Ragveil"] = 325,
    ["Terocone"] = 325,
    ["Flame Cap"] = 335,
    ["Ancient Lichen"] = 340,
    ["Netherbloom"] = 350,
    ["Nightmare Vine"] = 365,
    ["Mana Thistle"] = 375,
}

PST.Data.Lockboxes = {
    ["Ornate Bronze Lockbox"] = 1,
    ["Battered Junkbox"] = 1,
    ["Heavy Bronze Lockbox"] = 25,
    ["Worn Junkbox"] = 70,
    ["Iron Lockbox"] = 70,
    ["Strong Iron Lockbox"] = 125,
    ["Sturdy Junkbox"] = 175,
    ["Steel Lockbox"] = 175,
    ["Reinforced Steel Lockbox"] = 225,
    ["Mithril Lockbox"] = 225,
    ["Thorium Lockbox"] = 225,
    ["Heavy Junkbox"] = 250,
    ["Eternium Lockbox"] = 225,
    ["Strong Junkbox"] = 300,
    ["Khorium Lockbox"] = 325,
}

PST.Data.LockboxReferenceItems = {
    ["Ornate Bronze Lockbox"] = 4632,
    ["Heavy Bronze Lockbox"] = 4633,
    ["Iron Lockbox"] = 4634,
    ["Strong Iron Lockbox"] = 4636,
    ["Steel Lockbox"] = 4637,
    ["Reinforced Steel Lockbox"] = 4638,
    ["Mithril Lockbox"] = 5758,
    ["Thorium Lockbox"] = 5759,
    ["Eternium Lockbox"] = 5760,
    ["Khorium Lockbox"] = 31952,
    ["Battered Junkbox"] = 16882,
    ["Worn Junkbox"] = 16883,
    ["Sturdy Junkbox"] = 16884,
    ["Heavy Junkbox"] = 16885,
    ["Strong Junkbox"] = 29569,
}

PST.Data.LockedObjects = {
    ["Practice Lockboxes"] = 1,
    ["Buccaneer's Strongbox"] = 1,
    ["Burial Chest"] = 1,
    ["Primitive Chest"] = 20,
    ["Cozzle's Footlocker"] = 160,
    ["Scarlet Footlocker"] = 250,
    ["Wicker Chest"] = 300,
}

PST.Data.LockpickableDoors = {
    ["Ironclad Cove Gate"] = { skill = 1, location = "The Deadmines" },
    ["Gnomeregan Workshop Door"] = { skill = 150, location = "Gnomeregan" },
    ["Scarlet Monastery Armory Door"] = { skill = 175, location = "Scarlet Monastery" },
    ["Scarlet Monastery Cathedral Door"] = { skill = 175, location = "Scarlet Monastery" },
    ["Searing Gorge Gate"] = { skill = 225, location = "Loch Modan / Searing Gorge" },
    ["East Garrison Door"] = { skill = 250, location = "Blackrock Depths" },
    ["Prison Cells"] = { skill = 250, location = "Blackrock Depths" },
    ["Shadowforge Gate"] = { skill = 250, location = "Blackrock Depths" },
    ["Shadowforge Lock"] = { skill = 250, location = "Blackrock Depths" },
    ["Scholomance Door"] = { skill = 280, location = "Scholomance" },
    ["Scarlet Bastion Door"] = { skill = 300, location = "Stratholme" },
    ["Stratholme Gate"] = { skill = 300, location = "Stratholme" },
    ["Crescent Door"] = { skill = 300, location = "Dire Maul" },
    ["Shattered Halls Door"] = { skill = 350, location = "Shattered Halls" },
    ["Shadow Labyrinth Gate"] = { skill = 350, location = "Shadow Labyrinth" },
    ["Arcatraz Door"] = { skill = 350, location = "The Arcatraz" },
    ["Karazhan Gatehouse Portcullis"] = { skill = 350, location = "Karazhan" },
    ["Karazhan Side Entrance"] = { skill = 350, location = "Karazhan" },
}
